/*
 * Copyright 2020 Prathab Murugan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.prathab.userservice.controllers;

import com.prathab.userservice.controllers.models.mapper.UserApiMapper;
import com.prathab.userservice.controllers.models.request.CreateUserRequest;
import com.prathab.userservice.controllers.models.response.CreateUserResponse;
import com.prathab.userservice.services.UserService;
import javax.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.env.Environment;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller for facilitating user actions.
 */
/**
 * is a RESTful controller that handles user-related actions. It has methods for
 * signing up new users and returning the status of the server. The class uses Lombok
 * to generate getters and setters for its fields, and it also includes Slf4j for
 * logging purposes.
 */
@RestController
@Slf4j
public class UserController {
  private final UserService userService;
  private final UserApiMapper userApiMapper;
  private final Environment environment;

  public UserController(UserService userService,
      UserApiMapper userApiMapper, Environment environment) {
    this.userService = userService;
    this.userApiMapper = userApiMapper;
    this.environment = environment;
  }

  /**
   * logs a message to the trace log and returns the string "Working".
   * 
   * @returns "Working".
   */
  @GetMapping("/users/status")
  public String status() {
    log.trace("Running on port{} with jwt_secret{}",
        environment.getProperty("local.server.port"),
        environment.getProperty("token.secret"));
    return "Working";
  }

  /**
   * maps a `CreateUserRequest` object to a `CreatedUserResponse` object through a
   * series of mappings, then creates a new user using the `userService`, and finally
   * returns the created user as a `ResponseEntity` with a status code of `CREATED`.
   * 
   * @param request CreateUserRequest object passed from the client to the server for
   * creating a new user account.
   * 
   * 	- `@Valid`: Indicates that the request body is validated using Java Beans validation.
   * 	- `@RequestBody`: Marks the request body as a direct input to the function.
   * 	- `CreateUserRequest`: The class representing the JSON/XML request data, which
   * contains the user details to be created.
   * 
   * @returns a `ResponseEntity` with a status of `HttpStatus.CREATED` and a body
   * containing the created user response.
   * 
   * 	- `ResponseEntity`: This is the generic type of the response entity, which is an
   * wrapper class around the actual response data. It provides the HTTP status code
   * and body, which are important for determining how the client should handle the response.
   * 	- `body`: This property contains the actual response data, which in this case is
   * a `CreateUserResponse`.
   * 	- `status`: This property contains the HTTP status code of the response, which
   * is set to `HttpStatus.CREATED` indicating that the request was successful and the
   * user account was created.
   * 
   * The various attributes of the `CreateUserResponse` object are:
   * 
   * 	- `id`: A unique identifier for the user account, which is generated by the server.
   * 	- `username`: The username chosen by the user during the sign-up process.
   * 	- `email`: The email address associated with the user account.
   * 	- `fullName`: The full name of the user.
   * 	- `phoneNumber`: The phone number associated with the user account (optional).
   */
  @PostMapping(
      path = "/users",
      produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE},
      consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}
  )
  public ResponseEntity<CreateUserResponse> signUp(@Valid @RequestBody CreateUserRequest request) {
    log.trace("Received SignUp request");
    var requestUserDto = userApiMapper.createUserRequestToUserDto(request);
    var createdUserDto = userService.createUser(requestUserDto);
    var createdUserResponse = userApiMapper.userDtoToCreateUserResponse(createdUserDto);
    return ResponseEntity.status(HttpStatus.CREATED).body(createdUserResponse);
  }
}
