package com.myhome.controllers.request;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Email;

/**
 * represents a data class for requesting password recovery with email address and
 * token for verification, as well as a new password to replace the previously recovered
 * password.
 * Fields:
 * 	- email (String): in the ForgotPasswordRequest class is of type String and is
 * used to store the user's email address for password reset purposes.
 * 	- token (String): in the ForgotPasswordRequest class represents a unique identifier
 * generated by the system for the user's account.
 * 	- newPassword (String): in the ForgotPasswordRequest class is a String variable
 * representing a password provided by the user for resetting their account login credentials.
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
public class ForgotPasswordRequest {
  @Email
  public String email;
  public String token;
  public String newPassword;
}
